#!/bin/bash

# ホテルコンシェルジュ向け旅行プラン作成API
# cURLテストコマンド集

echo "=============================================="
echo "ホテルコンシェルジュ向け旅行プラン作成API"
echo "cURLテストコマンド"
echo "=============================================="
echo ""

# APIサーバーのベースURL
BASE_URL="http://localhost:5001/api"

echo "事前準備: 別ターミナルで以下のコマンドを実行してサーバーを起動してください"
echo "cd backend && python app.py"
echo ""
echo "サーバー起動後、以下のコマンドを実行してください"
echo ""

echo "----------------------------------------------"
echo "1. ヘルスチェック"
echo "----------------------------------------------"
echo "curl -X GET \"$BASE_URL/health\""
echo ""

echo "----------------------------------------------" 
echo "2. 候補地取得API"
echo "----------------------------------------------"
echo "# 顧客C001の推薦観光地を取得"
echo "curl -X GET \"$BASE_URL/destinations?customer_id=C001&weather=sunny&season=spring\""
echo ""
echo "# 顧客C002の推薦観光地を取得（興味タグ: #温泉）"
echo "curl -X GET \"$BASE_URL/destinations?customer_id=C002&weather=cloudy&season=winter\""
echo ""
echo "# 顧客C005の推薦観光地を取得（VIP顧客）"
echo "curl -X GET \"$BASE_URL/destinations?customer_id=C005&weather=sunny&season=summer\""
echo ""

echo "----------------------------------------------"
echo "3. ルート取得API"
echo "----------------------------------------------"
echo "# 首里城 → 国際通りの2地点ルート"
echo "curl -X POST \"$BASE_URL/route\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"destinations\": ["
echo "      {\"destination_id\": \"D001\", \"latitude\": 26.2173, \"longitude\": 127.7199},"
echo "      {\"destination_id\": \"D003\", \"latitude\": 26.2124, \"longitude\": 127.6792}"
echo "    ]"
echo "  }'"
echo ""

echo "# 首里城 → 国際通り → 美ら海水族館の3地点ルート"
echo "curl -X POST \"$BASE_URL/route\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"destinations\": ["
echo "      {\"destination_id\": \"D001\", \"latitude\": 26.2173, \"longitude\": 127.7199},"
echo "      {\"destination_id\": \"D003\", \"latitude\": 26.2124, \"longitude\": 127.6792},"
echo "      {\"destination_id\": \"D002\", \"latitude\": 26.6940, \"longitude\": 127.8779}"
echo "    ]"
echo "  }'"
echo ""

echo "# 沖縄北部ルート（美ら海水族館 → 古宇利島 → 今帰仁城跡）"
echo "curl -X POST \"$BASE_URL/route\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"destinations\": ["
echo "      {\"destination_id\": \"D002\", \"latitude\": 26.6940, \"longitude\": 127.8779},"
echo "      {\"destination_id\": \"D006\", \"latitude\": 26.7567, \"longitude\": 127.9678},"
echo "      {\"destination_id\": \"D018\", \"latitude\": 26.6917, \"longitude\": 127.9283}"
echo "    ]"
echo "  }'"
echo ""

echo "----------------------------------------------"
echo "4. 旅程作成API"
echo "----------------------------------------------"
echo "# まず上記のルート取得APIを実行してルートデータを取得"
echo "# そのレスポンスのrouteオブジェクトを使用して旅程を作成"
echo ""
echo "# サンプル旅程作成（首里城→国際通りルート用）"
echo "curl -X POST \"$BASE_URL/itinerary\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"route\": {"
echo "      \"geometry\": null,"
echo "      \"total_distance_km\": 5.12,"
echo "      \"total_duration_minutes\": 12.8,"
echo "      \"waypoints\": ["
echo "        {"
echo "          \"order\": 1,"
echo "          \"destination_id\": \"D001\","
echo "          \"name\": \"首里城\","
echo "          \"latitude\": 26.2173,"
echo "          \"longitude\": 127.7199,"
echo "          \"estimated_stay_minutes\": 90,"
echo "          \"travel_to_next\": {"
echo "            \"distance_km\": 5.12,"
echo "            \"duration_minutes\": 12.8"
echo "          }"
echo "        },"
echo "        {"
echo "          \"order\": 2,"
echo "          \"destination_id\": \"D003\","
echo "          \"name\": \"国際通り\","
echo "          \"latitude\": 26.2124,"
echo "          \"longitude\": 127.6792,"
echo "          \"estimated_stay_minutes\": 60,"
echo "          \"travel_to_next\": null"
echo "        }"
echo "      ]"
echo "    },"
echo "    \"start_time\": \"09:00\","
echo "    \"travel_date\": \"2024-03-15\""
echo "  }'"
echo ""

echo "----------------------------------------------"
echo "5. エラーテスト例"
echo "----------------------------------------------"
echo "# 存在しない顧客ID"
echo "curl -X GET \"$BASE_URL/destinations?customer_id=C999\""
echo ""
echo "# 不正なルート（1地点のみ）"
echo "curl -X POST \"$BASE_URL/route\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"destinations\": ["
echo "      {\"destination_id\": \"D001\", \"latitude\": 26.2173, \"longitude\": 127.7199}"
echo "    ]"
echo "  }'"
echo ""

echo "=============================================="
echo "使用方法:"
echo "1. このファイルを保存"
echo "2. chmod +x curl_test_commands.sh で実行権限付与"
echo "3. ./curl_test_commands.sh でコマンド一覧表示"
echo "4. 個別にコマンドをコピー＆ペーストして実行"
echo "=============================================="
